#!/usr/bin/env bash
# fixing docker issues
# Return Hello Holberton

sudo apt-get update -y
sudo apt-get install -y
sudo etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo etc/init.d/apache2 restart
