#!/usr/bin/env bash
# configuring the servers to listening on port 80 active IPv4 IPs
sudo sed -i "/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
